name: "CI"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  ci-merge:
    runs-on: ubuntu-latest
    container:
      image: docker-registry.wikimedia.org/bullseye:20221218
      options: --user root

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Wikimedia Bullseye image
        run: |
          apt-get update -y
          apt-get install python3-pip python3-dev python3-setuptools build-essential python3-enchant g++ gfortran git \
          liblapack-dev	libopenblas-dev libenchant-2-2 wget -y

      - name: Run all
        run: |
          make pip-install
          make setup-image
          make run-tests

    outputs:
      head-status: ${{ job.status }}
